apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-b
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/keenbytes/apps-of-apps-example
    targetRevision: HEAD
    path: apps/first-level/b
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}
